services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    image: ghcr.io/daerkle/oidsgvo:${WEBUI_DOCKER_TAG-latest}
    container_name: open-webui-dsgvo
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_ADMIN_EXPORT=false'
      - 'ENABLE_ADMIN_CHAT_ACCESS=false'
      - 'SCARF_NO_ANALYTICS=true'
      - 'DO_NOT_TRACK=true'
      - 'ANONYMIZED_TELEMETRY=false'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}