services:
  open-webui:
    image: ghcr.io/daerkle/oidsgvo:${WEBUI_DOCKER_TAG-latest}
    container_name: open-webui-dsgvo
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_ADMIN_EXPORT=false'
      - 'ENABLE_ADMIN_CHAT_ACCESS=false'
      - 'SCARF_NO_ANALYTICS=true'
      - 'DO_NOT_TRACK=true'
      - 'ANONYMIZED_TELEMETRY=false'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}